title: matt_wyz
author:
  name: Matthew W.
  email: matthew@mattwyz.xyz
  
description:
  (c) matthew w. 2023-2025
  Powered by Github Pages
  
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  
logo: /favicon.png



minima:
  skin: auto

  nav_page:
  - index.md
  - about.md
  - projects.md
  
  social_links:
    - title: Instagram
      icon: instagram
      url: "https://instagram.com/matt_wyz"
    - title: YouTube
      icon: youtube
      url: "https://youtube.com/@matt_wyz"
