title: matt_wyz
author:
  name: Matthew Wang
  email: matthew@mattwyz.xyz

description: >
  (c) Matthew Wang 2023-2025.
  Powered by Github Pages

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: auto
  
  nav_pages:
    - index.md
    - about.md
    - projects.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false
  
  social_links:
    - title: Instagram
       icon: instagram
       url: "https://instagram.com/matt_wyz"
     - title: YouTube
       icon: youtube
       url: "https://youtube.com/@matt_wyz"
