title: matt_wyz
author:
  name: Matthew Wang
  email: matthew@mattwyz.xyz

description: >
  (c) matthew w. 2023-2025
  Powered by Github Pages

theme: jekyll/minima

plugins:
  - jekyll-remote-theme

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  social_links:
    - title: Instagram
      icon: instagram
      url: "https://instagram.com/matt_wyz"
    - title: YouTube
      icon: youtube
      url: "https://youtube.com/@matt_wyz"
